/*
 * Please do not edit this file.
 * It was generated using PAB's VML system.
 */

#include <alg/stout_smear_arg.h>
CPS_START_NAMESPACE
	 bool StoutSmearArg::Encode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_ENCODE)) return false;
		 if ( !Vml(&vmls,instance) ) return false;
		 vmls.Destroy(); return true;
	 }

	 bool StoutSmearArg::Decode(char *filename,char *instance){
		 VML vmls;
		 if ( !vmls.Create(filename,VML_DECODE)) return false;
		 if ( !Vml(&vmls,instance)) return false;
		 vmls.Destroy(); return true;
	 }
	 bool StoutSmearArg::Vml(VML *vmls,char *instance){
		 if(!vml_StoutSmearArg(vmls,instance,this)) return false;
	 return true;
	}


bool_t
vml_StoutSmearArg (VML *vmls, char *name,StoutSmearArg *objp)
{
	 vml_class_begin(vmls,"StoutSmearArg",name);
	 if (!vml_Float (vmls, "tolerance", &objp->tolerance))
		 return FALSE;
	 if (!vml_int (vmls, "orthog", &objp->orthog))
		 return FALSE;
	 if (!vml_Float (vmls, "coef", &objp->coef))
		 return FALSE;
	 vml_class_end(vmls,"StoutSmearArg",name);
	return TRUE;
}
CPS_END_NAMESPACE
